version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free
    container_name: oracle-free
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_PASSWORD: Oracle123
    restart: unless-stopped

  streamlit-app:
    build: ./app
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      - DB_USER=SYSTEM
      - DB_PASSWORD=Oracle123
      - DB_HOST=oracle-db
      - DB_PORT=1521
      - DB_SERVICE=XEPDB1
    depends_on:
      - oracle-db
    working_dir: /app
    command: streamlit run app.py --server.port=8501
